language: java
jdk: openjdk11
addons:
  sonarcloud:
    organization: "akihiro08key" # the key of the org you chose at step #3
    token:
      secure: $SONARCLOUD
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage sonar:sonar -Dsonar.projectKey=Akihiro08_adder-integration
after_deploy:
- echo "done building, testing and deploying"

